# Generated by Django 2.2.2 on 2020-04-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='traction',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='offroad_slipperiness',
            field=models.DecimalField(decimal_places=1, default=0.6, max_digits=2),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='road_slipperiness',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='track',
            name='check_point_count',
            field=models.IntegerField(default=0, help_text='Number of check points on track (not counting starting/finnish line).'),
        ),
        migrations.AlterField(
            model_name='track',
            name='starting_azimuth',
            field=models.IntegerField(default=0, help_text='Orientation of a car on starting line (°).'),
        ),
        migrations.AlterField(
            model_name='track',
            name='starting_position_x',
            field=models.IntegerField(default=0, help_text='Positioning of track from left window edge so that car is on starting line (px).'),
        ),
        migrations.AlterField(
            model_name='track',
            name='starting_position_y',
            field=models.IntegerField(default=0, help_text='Positioning of track from top window edge so that car is on starting line (px).'),
        ),
    ]
